### ISSUE TITLE
The advance qustion about how to use the pmemkv-java?

### ISSUE THREAD

**Issue by brotherlu-xcq** [pmem/pmemkv-java#158]
# QUESTION: 
The advance qustion about how to use the pmemkv-java? 
## Details

- How can I update the exsited value in database? like append value the existed value.
- How can I read the designated value I want? 
- the ValueCallback catch all the size of the value one time or just the catch the value at the fixed size many times?

could anyone help me on these? tks.

**Comment by igchor** [comment]
Hi,

1. Right now, you can only overwrite the value entirely by using put. We are currently working on exposing iterators which would allow you to modify only part of the value or implement something similar to compare_and_swap. You can check out iterators C++ API for iterators: https://pmem.io/pmemkv/master/manpages/libpmemkv_iterator.3.html
 
2. I'm not sure if I understand this question correctly. Do you mean how to read an element with a specified key? To do that you can just call getCopy(key) like in this example: https://github.com/pmem/pmemkv-java/blob/master/examples/StringExample/src/main/java/StringExample.java#L41 or call get(key, callback) to avoid any copies

3. ValueCallback is only used in get() method. If you call get(key) and there an element with such key in the database the callback will be called once (and you can read the entire value within this callback). Otherwise, the callback will not be called at all.

Please let me know if you have any further questions.

**Comment by brotherlu-xcq** [comment]
@igchor thank you so much^_^. 
about question 2. I want to learn how can I read the partial data I  want, instead of read all data. 
about quesion 3. you mean that the ValueCallback will accept all value of the key I want query one time, not partial value? is that right?

**Comment by lukaszstolarczuk** [comment]
Hi @brotherlu-xcq,

as igchor mentioned previously - for now, we only support reading (and writing) the entire value. It's not possible to read partial value.
And yes - the ValueCallback will accept **all** value data of the key.

Pretty soon we should have the possibility to read partial data using iterators (as mentioned by igchor), but that's currently in progress of development.

**Comment by brotherlu-xcq** [comment]
thank you so much, @igchor and @lukaszstolarczuk . the answers from you have solved my question. I will close this issue. looking forward to your new feature to support my scene.
